theme: minima
title: EDCompanion
description: An Android companion app for Elite Dangerous
author:
  name: corenting
  email: edcompanion@corenting.fr
 
minima:
  social_links:
    github: corenting/EDCompanion
